using Bolt;
using UnityEngine;

namespace SuperShooter
{

    // IInteractableState was generated by Bolt when the assembly was compiled.
    // Open the Assets -> Bolt -> Assets window to see where these definitions are found.
    [RequireComponent(typeof(BoltEntity))]
    public class NetworkBasicBehaviour : Bolt.EntityBehaviour<IInteractableState>
    {

        /// <summary>The equivelent of the <see cref="UnityEngine.MonoBehaviour.Start()"/> method,
        /// but is called after the GameObject has been setup inside Bolt and exists on the network.</summary>
        public override void Attached()
        {

            state.SetTransforms(state.InteractableTransform, transform);

        }

        //public override void SimulateOwner()
        //{
        //    var speed = 4f;
        //    var movement = Vector3.zero;

        //    if (Input.GetKey(KeyCode.W)) { movement.z += 1; }
        //    if (Input.GetKey(KeyCode.S)) { movement.z -= 1; }
        //    if (Input.GetKey(KeyCode.A)) { movement.x -= 1; }
        //    if (Input.GetKey(KeyCode.D)) { movement.x += 1; }

        //    if (movement != Vector3.zero)
        //    {
        //        Debug.Log("Movement " + movement.ToString());
        //        transform.position = transform.position + (movement.normalized * speed * BoltNetwork.FrameDeltaTime);
        //    }
        //}


    }
}